### PR TITLE
Added TOC using npm module doctoc

### PR DESCRIPTION
**Pull request by RichardLitt**
This should automatically update. All it takes on the maintainer's end
is to `npm install -g doctoc`, and run it once in the file. I like
the look of it, and I think this solves the issue in one command nicely.
This is made to deal with #10.

### CODE REVIEW

**Comment by k88hudson** [comment]
@RichardLitt feel free to merge when this is ready to go

**Comment by RichardLitt** [comment]
Cool. Let's get the other PRs merged in first.

**Comment by RichardLitt** [comment]
Rebased and merged.

**Comment by unixorn** [comment]
I didn't know about doctoc before seeing this PR, now I'm using it in a couple of my own projects. Thanks @RichardLitt.

**Comment by RichardLitt** [comment]
Yeah. It's pretty nifty. Got some issues - see the 'code block'  in the thing here - but I like it.

**Pull request merged**
