### PR TITLE
Lint fixes

### PR DESCRIPTION
**Pull request by flexdinesh**
Fixed a few lint warnings. Used markdownlint-cli https://github.com/igorshubovych/markdownlint-cli to lint the file.

### CODE REVIEW

**Comment by flexdinesh** [comment]
Absolutely. I didn't run `doctoc`. I will ignore the rule to lint TOC and amend this commit.

**Comment by RichardLitt** [comment]
@flexdinesh Word on this?

**Comment by RichardLitt** [comment]
Ping @flexdinesh.

**Comment by flexdinesh** [comment]
@RichardLitt I was away for a month. I am going to close this PR and create a new one after linting the latest Readme.md

**Pull request closed without merging**
