### PR TITLE
Improve "discard specific unstaged changes" steps

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Why not just include a third strategy?

**Comment by PeterDaveHello** [comment]
If it's much more easier, why more steps?

**Comment by RichardLitt** [comment]
Because the guide isn't about steps alone, it's about the different ways of doing it and comprehension of how each are different. The stash is also a very useful tool at times, because it allows you to use it as a stack, which checkout doesn't. They do different things.

**Comment by PeterDaveHello** [comment]
As you say, they do different things, we can use `stash` a better way, for the title of this part, IMO, it's more suitable to not use `stash`, if this guide is about more ways, there are still many, but may not be properly, anyway, maybe I'll just close this one, thanks.

**Comment by RichardLitt** [comment]
There's no need to close this; it's a good suggestion. I think it should actually be the _first_ option. I just don't think we need to remove the others. 

Please, if you like, reopen it.

**Comment by PeterDaveHello** [comment]
Reopened, feel free to revise.

**Comment by RichardLitt** [comment]
Merged in 2a86ef478ee903ccef825e160ce40e9a7b3c8c86. Thank you, @PeterDaveHello

**Pull request merged**
