### PR TITLE
Added SublimeMerge client

### PR DESCRIPTION
**Pull request by MattMattV**
Creators of Sublime Text recently launched a Git client, it has a lot of potential !

I think it has its place in this list :smiley: 

Please tell me if my phrasing is wrong

### CODE REVIEW

**Comment by MattMattV** [comment]
@RichardLitt I delivered a correction :smiley:

**Comment by RichardLitt** [comment]
Needs an `s` on provides still. :)

**Comment by MattMattV** [comment]
Here are another correction, sorry for my lack of awareness :dizzy_face:

**Comment by RichardLitt** [comment]
:) Got it! Thanks!

**Pull request merged**
