### PR TITLE
Add example of making command aliases.

### PR DESCRIPTION
**Pull request by unixorn**
This was something I showed some of our interns that they found helpful. For #26.

### CODE REVIEW

**Comment by k88hudson** [comment]
Thanks @unixorn! Sorry for the delay... @RichardLitt is helping me revive the project a bit

**Comment by unixorn** [comment]
@k88hudson if you need another helper, I'm willing. I'm a collaborator on dotfiles.github.io.

**Comment by k88hudson** [comment]
@unixorn cool,  can you ping me on irc? (i'm always on mozilla as k88hudson, can do freenode too)

**Comment by unixorn** [comment]
@k88hudson, sure, let me go set up an account on mozilla. I'm also curiousbiped on twitter

**Pull request merged**
