### PR TITLE
Add Git Extensions to GUI clients

### PR DESCRIPTION
**Pull request by NRKirby**
Add [Git Extensions](https://github.com/gitextensions/gitextensions) to GUI clients section.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Rebase? That typo was fixed. :)

**Comment by NRKirby** [comment]
Ok, was just about to close this and open a new one. Will try rebasing now (not done it before!).

**Comment by RichardLitt** [comment]
It's actually pretty fun, and it's a good skill to learn! Let me know if you need help with it - if the section here on it doesn't help, add to it. :)

**Comment by NRKirby** [comment]
I've not got time to learn how to rebase now (it's getting late here). Closing this PR and will create a new one

**Pull request closed without merging**
