### PR TITLE
Minor changes to removing the file from last commit

### PR DESCRIPTION
**Pull request by pirj**
More specific removal of a file from a commit.

    git add -A

will add all the files, which might be undesirable, this may happen when `autoStash` is on.

To avoid editing the commit message again, a `--no-edit` may be used.

### CODE REVIEW

**Comment by k88hudson** [comment]
Awesome, this is definitely better. Can you add a short explaination that the  `--no-edit` refers to the commit message in the description?

**Comment by pirj** [comment]
@k88hudson added it:

> To avoid editing the commit message again, a --no-edit may be used.

**Comment by RichardLitt** [comment]
@pirj Thanks. I think she meant in the commit - could you add the note to the section you're editing?

**Comment by pirj** [comment]
@RichardLitt Just to avoid any ambiguity, commit message or README.md?

**Comment by RichardLitt** [comment]
In the README. :)

**Comment by pirj** [comment]
Done. Ready to be merged?

**Comment by RichardLitt** [comment]
Yep! Done and merged. Thank you!

**Pull request merged**
