### PR TITLE
add cheat sheet

### PR DESCRIPTION
**Pull request by shubham171294**
I've added the cheat sheet. Kindly review and merge the PR.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Sorry, @shubham171294 - I meant it would be great if you could manually add the sections in the cheatsheet which are not in the README, to the README. That means copying the text in the PDF, and expanding it where needed.

**Comment by shubham171294** [comment]
Ok. I'll do it.

**Comment by shubham171294** [comment]
Hi @RichardLitt . I've made a sample commit. Please check if it correct or some changes are required. I can proceed with the updated formatting after finalizing.

**Comment by RichardLitt** [comment]
Thanks @shubham171294. Close - but I'd suggest, instead of making it's own section or referring the git cheat sheet at all - to copy the sections which are relevant into their own sections. For instance: 

```
<a href="#clone-an-exising-repo"></a>
## Clone an existing repository

To clone an existing repo, run this:

  ```sh
  $ git clone ssh://user@domain.com/repo.git
  ```
```

And then add them to the TOC and place them accordingly in the file.

**Comment by qWici** [comment]
@RichardLitt 
I created two pdf files
1 - via [MarkdownToPDF](http://www.markdowntopdf.com/)
2 - via node module [markdown-pdf](https://www.npmjs.com/package/markdown-pdf)
We can make a vote. If the community says it's a good idea - you'll need to find or write your own auto-generator.

[README-via-markdowntopdf-com.pdf](https://github.com/k88hudson/git-flight-rules/files/1524059/README-via-markdowntopdf-com.pdf)
[README-via-node-markdown-pdf.pdf](https://github.com/k88hudson/git-flight-rules/files/1524057/README-via-node-markdown-pdf.pdf)

**Comment by RichardLitt** [comment]
@shubham171294 I've opened a new PR in #174 showing what I meant. If you'd like to keep helping out, jump in and PR off of that branch! For now, I am closing this for both being stale and for being superseded by #174.

**Pull request closed without merging**
