### PR TITLE
Added Git Cop as a quality control tool.

### PR DESCRIPTION
**Pull request by bkuhlmann**
## Overview

Added a **Code Quality** section to the README with a link to [Git Cop](https://github.com/bkuhlmann/git-cop) which helps enforce high quality Git commits (it is also easily customizable).

## Details

It's equally important to maintain a consistent style for your code
*including* your Git history. This leads to a Git history that is
easier to read, debug, and provides well-maintained breadcrumbs for
figuring out why/how the code evolved to the state it is in today.

### CODE REVIEW

**Comment by RichardLitt** [comment]
I've used Git Cop before with ipfs/ipfs - thanks for making it, @bkuhlmann! But I'm not sure it belongs in this repository, largely because it doesn't fit under the rubric of "Is this a git flight rule?" This list is mostly about what to do after having done something, not how to do things in the future so that you don't mess things up. I think that [awesome-git](https://github.com/dictcp/awesome-git) would probably cover that more.

**Comment by RichardLitt** [comment]
Wait, this doesn't seem to be the same as https://github.com/git-cop. Am I missing something?

**Comment by bkuhlmann** [comment]
Correct. This is very different than `Git Cop`, the service. Mine is an open source Ruby gem that is free to use. The service and my gem are not related or affiliated. You can wire it up as a Git Hook and/or add it to your CI builds. I use it on all my open source work in addition to the development team that I lead.

I like the value this project adds in terms of getting yourself out of a bad mess. I think listing Git Cop as a code quality tool can help keep people from getting into some of these messes in the first place. ...but I respect your opinion if you don't feel this adds any value to this project -- I thought I'd contribute in case it did.

**Comment by RichardLitt** [comment]
I feel it would add value, but I also feel it is out of scope. Thank you for suggesting it, anyway!

**Pull request closed without merging**
