### PR TITLE
WIP - Start translation into Russian

### PR DESCRIPTION
**Pull request by qWici**
I started working on the translation, if someone had a desire, I would be happy to help

### CODE REVIEW

**Comment by qWici** [comment]
Someone please add "PR in progress" and "Need help" labels

**Comment by kingbangla191** [comment]
It seems in this section, you discard commited change, or am I misunderstanding ?

**Comment by RichardLitt** [comment]
@kingbangla191 Wait until this is ready to go before approving. It's currently still in progress!

**Comment by qWici** [comment]
Russian translation added in #161

**Pull request closed without merging**
