### PR TITLE
Discard local uncommitted changes

### PR DESCRIPTION
**Pull request by jquintus**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Good additions!

**Comment by flexdinesh** [comment]
@RichardLitt How is this different from "_I want to discard my local, uncommitted changes_" section? Both titles mean the same, although "_I want to discard my local, uncommitted changes_" actually can discard local committed changes too.

**Comment by jquintus** [comment]
Thanks for pulling this in so quickly.

**Comment by RichardLitt** [comment]
@flexdinesh It is pretty similar. However, this helps clarify a bit further for specific uses. If that's true about uncommitted changes, let's fix that. Totally happy to review another PR. :)

**Pull request merged**
