### PR TITLE
Git shortcuts

### PR DESCRIPTION
**Pull request by a6delali**
Let's say you're comfortable with what the above commands are doing, you might want to create some shortcuts for Git Bash. This allows you to work a lot faster by doing complex tasks in really short commands.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks, @a6delali. We cover many of these in the git aliases section, and I'm not sure that this improves on that section. As well, this doesn't relate to git, itself, but rather to using Bash. I'm not sure that the scope creep is justified, as all of the things you suggest could be put in the `.gitconfig` file. 

Would you like to check and make sure that we aren't missing any good aliases in the aliases section? Or could you explain why another section is justified? Thanks.

**Comment by a6delali** [comment]
The simplest way to add an alias for a specific git command is to use a standard bash alias. the advantage of this is that you can define bash aliases that you can call with git <alias>. 
To resume certainly you can execute shell commands in a Git alias, but if your alias is doing more shell magic than Git magic, it’s probably better as a shell alias.

**Comment by RichardLitt** [comment]
Thanks for explaining your rationale, @a6delali. You're right that setting aliases so that you don't need to write `$ git` can be done more easily using Bash aliases, if you're using an OS that can use Bash. But I don't think that that is actually a use case that should be in git-flight-rules. I want to limit this list to things you can do with git, not with configuration on top of git. 

I might be wrong on this. I know that we mention `bfg` in here, which isn't exactly Git as far as I know. And I personally use bash aliases, too, so I'm not disagreeing with you that they're useful - just that they don't belong here.

Anyone else have any thoughts on this?

**Comment by RichardLitt** [comment]
It would be great to have a nod to Windows as well as Bash, here. We don't have to make this section massive; just how to effectively set an alias and a function. I would go as far as to remove the extra commands in this PR - only have one of each, to show how it works. @a6delali Does that sound fair, to you?

**Comment by a6delali** [comment]
@RichardLitt fair enough, I'll do the necessary changes. However am not a windows geek so I'll someone else do the job.

**Comment by twwilliams** [comment]
I'm happy to convert that into a bit of PowerShell. Should I wait for this PR to be merged and then create my own PR with the PowerShell bits on top of that?

**Comment by RichardLitt** [comment]
This is perfect, @a6delali. Thank you! 

@twwilliams Merged. Go ahead and make a new PR if you could. :)

**Pull request merged**
