### PR TITLE
Update Russian translations upto English source

### PR DESCRIPTION
**Pull request by buslov**
Need to check new links in the table of contents

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/598/ru/review/483)

### CODE REVIEW

**Comment by buslov** [comment]
GitLocalize adds some changes like:
image

**Comment by RichardLitt** [comment]
@buslov this all ready to go?

**Comment by buslov** [comment]
Yes, this is ready to go

**Comment by RichardLitt** [comment]
Can you approve your own PRs? Might be a good idea, in the future - unless we get another Russian person here. That's just to let us know it is good to merge. Thanks, @buslov.

**Pull request merged**
