### PR TITLE
Incorporate Git Cheatsheet

### PR DESCRIPTION
**Pull request by RichardLitt**
This is the beginnings of a PR incorporating the Git Cheatsheet, to solve #90. 

I've done the first two sections. If anyone would like to help out, grab the cheatsheet, add some sections, and PR agains this branch. Doing it all on my own would be onerous! Would be great to open this up to others to have the opportunity to learn, too.

### CODE REVIEW

**Comment by eamanu** [comment]
I would use a different .md to make the cheatsheet.

**Comment by RichardLitt** [comment]
@eamanu I do not understand. I'm not making a separate resource, but integrating an existing one.

**Comment by eamanu** [comment]
@RichardLitt Right! I was confused

**Comment by RichardLitt** [comment]
New contributors: don't be scared of the conflict. Let me know if you'd like me to update it before PRing off of this branch.

**Comment by RichardLitt** [comment]
Rebased and merged.

**Pull request merged**
