### PR TITLE
Add a few recipes

### PR DESCRIPTION
**Pull request by dandv**
Nice doc! How did you get two thousand stars for it?

### CODE REVIEW

**Comment by k88hudson** [comment]
@dandv thanks! sorry for the delay on the review :sob:

**Comment by RichardLitt** [comment]
@dandv Add in the warns that @bor suggested, rebase against `master`, and I think we're all set to merge this in. :)

**Comment by dandv** [comment]
@RichardLitt It's been too many months for me to remember what this was about in the first place, so someone else might be better at this than me :) @k88hudson ?

**Comment by RichardLitt** [comment]
@dandv No worries! Got it. Merged. Thanks.

**Pull request merged**
