### PR TITLE
Feature/improve user contribution

### PR DESCRIPTION
**Pull request by sotayamashita**
What about to execute `doctoc` on pre-commit automatically?

### CODE REVIEW

**Comment by RichardLitt** [comment]
This is a good idea. But does this run on pre-commit? Did you mean to include a hook, somewhere? As it is, we'll have to manually run `npm run test`, unless I'm missing something.

**Comment by sotayamashita** [comment]
@RichardLitt You need to run `npm i` and it must setup pre-commit.  Does it make sense?

**Comment by RichardLitt** [comment]
@sotayamashita Getting an odd npm error. I've opened an issue there.

**Comment by sotayamashita** [comment]
@RichardLitt :thinking: I also investigate it.

**Comment by qWici** [comment]
@RichardLitt @sotayamashita Open new PR #191, check please =)

**Comment by RichardLitt** [comment]
@sotayamashita I've got this working now. However, it edits the TOC after I commit, and doesn't add the ToC edits to the commit. Do you think we can change that?

**Comment by RichardLitt** [comment]
Related to #191.

**Comment by RichardLitt** [comment]
I'm rethinking this. It fails if you don't have node installed, and if you don't have doctoc installed. I don't think I want this - while it's great for the maintainers to be able to add content, this is a barrier to entry for people who don't have node on their machines and don't know what to do here. The highest priority for this list is sourcing good content from potential writers, and I want to facilitate that as much as possible. So, I am going to take on a bit more effort on the side of the maintainers - running doctoc as needed - to help out that effort. 

Thanks for the work, though!

**Pull request closed without merging**
