### PR TITLE
Be more specific about HEAD^ vs HEAD~

### PR DESCRIPTION
**Pull request by Tatsujinichi**
The text as it is kind of implies that HEAD^2 would be equivalent to HEAD~2.  I think it it worth adding a little more detail here.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Fair. I think this needs a little bit more - can you add a sentence showing that `HEAD~2` points to the first parent's first parent, while `HEAD^2` specifies the first parent's second parent?

More on this: http://www.paulboxley.com/blog/2011/06/git-caret-and-tilde

**Comment by Tatsujinichi** [comment]
My impression is that this document is not a substitute for the official documentation.  But should be    
a sparse cheat sheet with short solutions to common problems.  Therefore I should not be overly verbose.  I think this is already on the borderline of saying too much.

**Comment by RichardLitt** [comment]
Hmm. Fair. @k88hudson What do you think?

**Comment by drj11** [comment]
Now I've learnt (thanks @RichardLitt ) about the difference between `thing^` and `thing~` I think that it's never worth teaching novices `HEAD^` and I should only ever use `HEAD~`.

In particular: `HEAD~~` is the same as `HEAD~2` and is often useful (the grandparent). `HEAD^^` (grandparent) is _not_ the same as `HEAD^2` (second parent when it exists) and I think the difference will only confuse novices.

**Comment by k88hudson** [comment]
@Tatsujinichi @RichardLitt Personally, I wouldn't go with an extended explanation with examples here, I'd just briefly mention that `HEAD~2` is not equivalent to `HEAD^2`. Something like:

```
This stands for the first parent of `HEAD`, similarly `HEAD^2` stands for the
second parent of the commit (merges can have 2 parents).
Note that `HEAD^2` is **not** the same as `HEAD~2`
(see [this link](http:....) for more information).
```
Even without the link, I think that would give folks enough context for further googling if necessary.

**Comment by RichardLitt** [comment]
Thanks @Tatsujinichi!

**Pull request merged**
