### PR TITLE
Add "I need to undo my last commit"

### PR DESCRIPTION
**Pull request by stuartpb**

### CODE REVIEW

**Comment by unixorn** [comment]
This only works if you haven't pushed. If you have pushed, the only truly safe thing to do is `git revert SHAofBadCommit`. That will create a new commit that undoes all the previous commit's changes.

**Comment by stuartpb** [comment]
@unixorn Or, if the branched you pushed to is rebase-safe (ie. other devs aren't expected to pull from it), you can just `git push -f`.

**Comment by unixorn** [comment]
It's probably best to clarify when the `git reset` is safe to use and when it isn't in the same paragraph you're suggesting using it.

**Comment by RichardLitt** [comment]
Agreed. @stuartpb, mind editing this PR?

**Comment by RichardLitt** [comment]
@stuartpb Let me know if you want me to do it, I can merge this and add the text. :)

**Comment by RichardLitt** [comment]
Thanks! All good. Merged.

**Comment by stuartpb** [comment]
I think `SHAofBadCommit` should just be `HEAD`, considering the context.

**Comment by RichardLitt** [comment]
Yeah, that would work. 

And we need to make better headings, actually. We've only just gotten down to 0 PRs for the first time, possibly ever, so now is the best time to reorganize. 

A new PR would be great.

**Pull request merged**
