### PR TITLE
WIP - Add french translation

### PR DESCRIPTION
**Pull request by aloisdg**
A coworker doesnt bother to read the english version. So here I am. Hope it will be helpful.
This is a work in progress. I just started. Any help is welcome.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Nice! Sounds good to me. We're using GitLocalize to help with translations. Let me know if you're signed up there, and I can add you as the moderator to help with translations. https://gitlocalize.com/repo/598

**Comment by Chouchen** [comment]
I relocated those translations into gitlocalize and added some new if that can help. 

I don't know this tool, did I do it the good way?

**Comment by RichardLitt** [comment]
Looks right to me! I added you as the moderator for French on Gitlocalize. At this point, I believe you could keep going until it is translated, and then PR. Sound good to you?

**Comment by Chouchen** [comment]
I guess I can give it a try!

**Comment by aloisdg** [comment]
Hello, Sorry I was off. Glad to see @Chouchen give it a try. :)

**Comment by aloisdg** [comment]
@Chouchen We can use the french glossary from the ProGit translation: https://github.com/progit/progit/blob/master/fr/glossaire-git.adoc

**Comment by Chouchen** [comment]
@aloisdg Good idea, I didn't know it existed and I was not sure if I needed to translate those technical terms or not.

**Comment by RichardLitt** [comment]
Hey all. This is a bit stale, so I am going to close it if there hasn't been significant effort in the next month. I appreciate the initial effort, but I don't want half a translation and a long-standing PR. Thanks.

**Comment by chriys** [comment]
@aloisdg @Chouchen the glossaire is awesome, although not yet completed. There is also the git book in french by navigating through the chapters and some `ctr+f` magic you can make your way through. Just added the translation of some technical terms. Some don't really have their counterpart in french tho.

**Pull request closed without merging**
